/**
Usuario: okysystem@okysystembd
Pasword: %UoV!4~9^z^Dj8%,^h)H

mysql -h okysystembd.mysql.database.azure.com -u okysystem@okysystembd -p --ssl
**/
CREATE TABLE CATEGORIA(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
	CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDCATEGORIA INTEGER NOT NULL,
	NOMBRE VARCHAR(45),
	PRECIO DECIMAL(4,2),
	DESCIPCION VARCHAR(100),
	IMAGEN VARCHAR(500),
	CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID),
	CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (ID)
);

CREATE TABLE USUARIO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(45),
	APELLIDO VARCHAR(45),
	EMAIL VARCHAR(100),
	TELEFONO INTEGER,
	PASSWORD VARCHAR(100),
	FECHA_REGISTRO DATE,
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);

CREATE TABLE METODO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
	CONSTRAINT METODO_PK PRIMARY KEY (ID)
);

CREATE TABLE PAGO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDUSUARIO INTEGER NOT NULL,
	IDMETODO INTEGER,
	CONSTRAINT PAGO_PK PRIMARY KEY (ID),
	CONSTRAINT PAGO_METODO_FK FOREIGN KEY (IDMETODO) REFERENCES METODO (ID),
	CONSTRAINT PAGO_USUARIO_FK FOREIGN KEY (IDUSUARIO)/**
Usuario: okysystem@okysystembd
Pasword: %UoV!4~9^z^Dj8%,^h)H

mysql -h okysystembd.mysql.database.azure.com -u okysystem@okysystembd -p --ssl
**/
CREATE TABLE CATEGORIA(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
	CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDCATEGORIA INTEGER NOT NULL,
	NOMBRE VARCHAR(45),
	PRECIO DECIMAL(4,2),
	DESCIPCION VARCHAR(100),
	IMAGEN VARCHAR(500),
	CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID),
	CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (ID)
);

CREATE TABLE USUARIO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(45),
	APELLIDO VARCHAR(45),
	EMAIL VARCHAR(100),
	TELEFONO INTEGER,
	PASSWORD VARCHAR(100),
	FECHA_REGISTRO DATE,
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);

CREATE TABLE METODO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100),
	CONSTRAINT METODO_PK PRIMARY KEY (ID)
);

CREATE TABLE PAGO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDUSUARIO INTEGER NOT NULL,
	IDMETODO INTEGER,
	CONSTRAINT PAGO_PK PRIMARY KEY (ID),
	CONSTRAINT PAGO_METODO_FK FOREIGN KEY (IDMETODO) REFERENCES METODO (ID),
	CONSTRAINT PAGO_USUARIO_FK FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE PEDIDO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDUSUARIO INTEGER NOT NULL,
	IDPAGO INTEGER NOT NULL,
	TOTALPEDIDO DOUBLE,
	PROGRAMADO DATE,
	DIRECCION VARCHAR(200),
	CONSTRAINT PEDIDO_PK PRIMARY KEY (ID),
	CONSTRAINT PEDIDO_PAGO_FK FOREIGN KEY (IDPAGO) REFERENCES PAGO (ID),
	CONSTRAINT PEDIDO_USUARIO_FK FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE PEDIDO_DETALLE(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	IDPEDIDO INTEGER NOT NULL,
	IDPRODUCTO INTEGER NOT NULL,
	CANTIDAD DOUBLE,
	PRECIO DOUBLE,
	DESCUENTO DOUBLE,
	CONSTRAINT PEDIDO_DETALLE_PK PRIMARY KEY (ID),
	CONSTRAINT DETALLE_PRODUCTO_FK FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (ID),
	CONSTRAINT DETALLE_PEDIDO_FK FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (ID)
);





