-- guanaco_bd.categories definition

CREATE TABLE `categories` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.payment_method definition

CREATE TABLE `payment_method` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.roles definition

CREATE TABLE `roles` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROL` varchar(20) NOT NULL,
  `CREATEDAT` datetime NOT NULL,
  `UPDATEDAT` datetime NOT NULL,
  `IMAGE` varchar(255) DEFAULT NULL COMMENT 'Image of rol',
  `ROUTE` varchar(180) NOT NULL COMMENT 'Route of rol in app ',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.users definition

CREATE TABLE `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(180) NOT NULL,
  `NAME` varchar(90) NOT NULL,
  `LASTNAME` varchar(90) NOT NULL,
  `PHONE` varchar(90) NOT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(90) NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `UPDATED_AT` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  UNIQUE KEY `PHONE` (`PHONE`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.orders definition

CREATE TABLE `orders` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDUSER` int(11) NOT NULL,
  `IDMETHOD` int(11) NOT NULL,
  `TOTALORDERS` double DEFAULT NULL,
  `SCHEDULE` date DEFAULT NULL,
  `ADDRESS` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ORDERS_USER_FK` (`IDUSER`),
  KEY `ORDERS_METHOD_FK` (`IDMETHOD`),
  CONSTRAINT `ORDERS_METHOD_FK` FOREIGN KEY (`IDMETHOD`) REFERENCES `payment_method` (`ID`),
  CONSTRAINT `ORDERS_USER_FK` FOREIGN KEY (`IDUSER`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.products definition

CREATE TABLE `products` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORYID` int(11) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `PRICE` decimal(4,2) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `IMAGE` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PRODUCTO_CATEGORY_FK` (`CATEGORYID`),
  CONSTRAINT `PRODUCTO_CATEGORY_FK` FOREIGN KEY (`CATEGORYID`) REFERENCES `categories` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.user_rol definition

CREATE TABLE `user_rol` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDROL` int(11) NOT NULL,
  `IDUSER` int(11) NOT NULL,
  `CREATEDAT` datetime NOT NULL,
  `UPDATEDAT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USERROL_ROLES` (`IDROL`),
  KEY `USERROL_USER` (`IDUSER`),
  CONSTRAINT `USERROL_ROLES` FOREIGN KEY (`IDROL`) REFERENCES `roles` (`ID`),
  CONSTRAINT `USERROL_USER` FOREIGN KEY (`IDUSER`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


-- guanaco_bd.order_detail definition

CREATE TABLE `order_detail` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDORDERS` int(11) NOT NULL,
  `IDPRODUCT` int(11) NOT NULL,
  `QUANTITY` double DEFAULT NULL,
  `PRICE` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  PRIMARY KEY (`ID`,`IDORDERS`),
  KEY `DETALLE_PRODUCTO_FK` (`IDPRODUCT`),
  KEY `DETALLE_ORDERS_FK` (`IDORDERS`),
  CONSTRAINT `DETAIL_ORDERS_FK` FOREIGN KEY (`IDORDERS`) REFERENCES `orders` (`ID`),
  CONSTRAINT `DETAIL_PRODUCTS_FK` FOREIGN KEY (`IDPRODUCT`) REFERENCES `products` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO guanaco_bd.roles (ROL,CREATEDAT,UPDATEDAT,IMAGE,ROUTE) VALUES
	 ('RESTAURANTE','2022-06-23 11:28:53','2022-06-23 11:28:53',NULL,'/restaurant/order/list'),
	 ('CLIENTE','2022-06-23 11:29:05','2022-06-23 11:29:05',NULL,'/client/products/list'),
	 ('REPARTIDOR','2022-06-23 11:29:05','2022-06-23 11:29:05',NULL,'/delivery/orders/list');