apiVersion: v1
kind: Service
metadata:
  name: guanacosapi-service
spec:
  selector:
    app: guanacos_api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
    nodePort: 31110